/* Add icons by appending Material Symbol names to a category. Russian metadata is separate. */
const ICON_CATEGORIES = [
['Популярные иконки для презентаций','Самые нужные знаки для слайдов и документов','search home menu close check add remove arrow_forward arrow_back star favorite person groups phone mail location_on calendar_today schedule info warning help settings download upload share link visibility edit delete lock payments trending_up bar_chart pie_chart lightbulb school'],
['Элементы интерфейса','Кнопки, стрелки, меню и элементы навигации','menu more_vert more_horiz close check add remove expand_more expand_less chevron_left chevron_right arrow_upward arrow_downward arrow_back arrow_forward first_page last_page refresh sync undo redo fullscreen fullscreen_exit open_in_new launch drag_indicator apps filter_list sort tune toggle_on toggle_off radio_button_checked check_box cancel done_all'],
['Люди и соцсети','Пользователи, команды и эмоции','person groups group person_add person_remove account_circle face mood sentiment_satisfied sentiment_dissatisfied diversity_1 diversity_2 diversity_3 handshake waving_hand thumb_up thumb_down public language share social_distance psychology accessibility child_care elderly woman man badge contacts supervisor_account engineering'],
['Действия','Частые команды и операции','search edit delete save print download upload content_copy content_paste content_cut add_circle remove_circle play_arrow pause stop restart_alt cached autorenew zoom_in zoom_out pan_tool touch_app login logout send reply forward archive inventory bookmark flag push_pin attach_file create brush build done select_all history restore publish'],
['Общение и связь','Почта, звонки, чаты и уведомления','phone call call_end smartphone mail email inbox drafts mark_email_read chat forum comment sms message notifications notifications_off alternate_email contact_mail contact_phone voicemail wifi cellular_alt signal_cellular_alt rss_feed campaign record_voice_over support_agent live_help speaker_phone video_call phonelink ring_volume'],
['Изображения и фото','Фото, палитры и работа с изображениями','image photo camera_alt photo_camera collections gallery_thumbnail palette color_lens crop rotate_left rotate_right flip brightness_6 contrast filter_hdr landscape portrait panorama add_a_photo image_search slideshow auto_awesome remove_red_eye hide_image broken_image gradient texture looks exposure center_focus_strong flash_on movie_creation animation'],
['Бизнес и финансы','Деньги, отчёты, рост и работа','payments attach_money currency_ruble euro currency_exchange account_balance account_balance_wallet savings credit_card receipt receipt_long point_of_sale shopping_cart storefront business work briefcase trending_up trending_down query_stats analytics bar_chart pie_chart monitoring timeline show_chart leaderboard calculate percent request_quote paid sell local_offer inventory_2 factory'],
['Карты и места','Адреса, маршруты и объекты на карте','location_on place map navigation near_me directions route explore my_location pin_drop where_to_vote flag room travel_explore public terrain satellite_alt layers streetview restaurant local_cafe hotel local_hospital local_library local_parking local_gas_station local_mall park museum church apartment domain home_work'],
['Текст и форматирование','Текстовые блоки и оформление документов','title text_fields format_bold format_italic format_underlined format_strikethrough format_size format_color_text format_align_left format_align_center format_align_right format_align_justify format_list_bulleted format_list_numbered format_quote notes subject article description insert_link link_off table_chart view_column space_bar functions superscript subscript wrap_text spellcheck translate short_text segment'],
['Аудио и видео','Музыка, видео и управление воспроизведением','play_arrow pause stop fast_forward fast_rewind skip_next skip_previous replay volume_up volume_down volume_off mic mic_off headphones speaker music_note queue_music album video_library movie videocam videocam_off closed_caption subtitles high_quality speed shuffle repeat podcast live_tv radio equalizer graphic_eq'],
['Транспорт','Автомобили и городской транспорт','directions_car car_rental taxi_alert local_taxi bus_alert directions_bus train tram subway flight two_wheeler motorcycle pedal_bike electric_bike electric_scooter airport_shuttle local_shipping delivery_dining commute traffic garage tire_repair car_repair ev_station no_crash sailing directions_boat rocket railway_alert'],
['Занятия и досуг','Спорт, творчество, покупки и отдых','sports_soccer sports_basketball sports_tennis sports_esports fitness_center hiking pool surfing skiing golf_course stadia_controller casino celebration cake restaurant local_bar coffee theater_comedy music_note piano draw palette book menu_book shopping_bag pets eco spa campground kayaking chess toys'],
['Android и система','Системные состояния и управление устройством','android settings power_settings_new restart_alt update system_update security shield bug_report memory storage battery_full battery_charging_full wifi bluetooth data_usage network_check signal_cellular_alt airplane_mode brightness_auto dark_mode light_mode language accessibility key keyboard mouse screenshot developer_mode code terminal integration_instructions dataset cloud cloud_done backup'],
['Техника и гаджеты','Компьютеры, экраны и устройства','devices computer laptop desktop_windows monitor smartphone tablet watch tv connected_tv keyboard mouse headphones headset speaker router scanner print camera phone_iphone phone_android smart_display smart_toy memory usb cable cast cast_connected dock gamepad thermostat sensors hub earbuds charging_station'],
['Безопасность','Защита, доступ и приватность','lock lock_open key vpn_key password shield security verified_user admin_panel_settings privacy_tip fingerprint policy gpp_good gpp_bad encrypted no_encryption visibility visibility_off warning report problem dangerous health_and_safety emergency passkey login logout person_off block do_not_disturb password'],
['Путешествия','Поездки, багаж, отели и направления','flight flight_takeoff flight_land luggage travel_explore hotel bed beach_access map public language passport connecting_airports departure_board train directions_boat sailing airport_shuttle local_taxi restaurant museum attractions hiking campground photo_camera explore navigation location_on festival currency_exchange'],
['Дом и быт','Комнаты, мебель и домашние дела','home apartment cottage house door_front living kitchen chair bed bedroom_parent bathroom shower bathtub weekend table_restaurant desk light cleaning_services vacuum local_laundry_service iron checkroom microwave blender coffee flatware grocery water_drop yard deck fence roofing garage foundation'],
['Умный дом','Датчики, климат и подключённые устройства','home_iot_device thermostat device_thermostat sensors sensor_door sensor_window lightbulb light_mode mode_fan air ac_unit heat_pump water_drop sprinkler nest_cam_indoor nest_cam_outdoor doorbell camera_outdoor detector_smoke detector_alarm electric_meter energy_savings_leaf wifi router hub smart_toy speaker tv remote_gen security lock blinds curtains'],
];

const RU_ICON_META = {
 search:['Поиск','поиск лупа найти искать'],home:['Дом','дом жильё главная'],phone:['Телефон','телефон звонок связь'],payments:['Деньги','деньги оплата финансы платёж'],person:['Человек','человек сотрудник пользователь'],groups:['Команда','команда люди сотрудники группа'],warning:['Внимание','внимание предупреждение опасность'],school:['Обучение','обучение образование школа'],settings:['Настройки','настройки параметры'],favorite:['Избранное','сердце любовь избранное'],star:['Звезда','звезда рейтинг'],mail:['Почта','почта письмо email'],location_on:['Место','место адрес геолокация'],calendar_today:['Календарь','календарь дата'],schedule:['Время','время часы расписание'],info:['Информация','информация сведения'],help:['Помощь','помощь вопрос'],download:['Скачать','скачать загрузить'],upload:['Загрузить','загрузить отправить'],share:['Поделиться','поделиться ссылка'],visibility:['Просмотр','глаз просмотр видимость'],edit:['Редактировать','карандаш изменить'],delete:['Удалить','корзина удалить'],lock:['Замок','замок безопасность'],trending_up:['Рост','рост график'],bar_chart:['Диаграмма','диаграмма график данные'],pie_chart:['Круговая диаграмма','диаграмма доли'],lightbulb:['Идея','идея лампочка'],menu:['Меню','меню навигация'],close:['Закрыть','закрыть крестик'],check:['Готово','галочка готово да'],add:['Добавить','плюс добавить'],remove:['Убрать','минус убрать'],arrow_forward:['Стрелка вправо','стрелка далее вправо'],arrow_back:['Стрелка влево','стрелка назад влево'],business:['Бизнес','бизнес компания офис'],work:['Работа','работа портфель'],analytics:['Аналитика','аналитика данные отчёт'],chat:['Чат','чат общение сообщение'],camera_alt:['Камера','камера фото'],image:['Изображение','изображение картинка фото'],play_arrow:['Воспроизвести','пуск видео играть'],pause:['Пауза','пауза остановить'],directions_car:['Автомобиль','машина автомобиль транспорт'],flight:['Самолёт','самолёт полёт путешествие'],security:['Безопасность','безопасность защита'],palette:['Палитра','палитра цвет дизайн'],shopping_cart:['Корзина','покупка корзина магазин'],public:['Мир','мир глобус земля'],language:['Язык','язык перевод мир'],key:['Ключ','ключ доступ безопасность'],wifi:['Wi-Fi','интернет сеть вайфай'],print:['Печать','печать принтер'],save:['Сохранить','сохранить дискета'],thumb_up:['Нравится','лайк нравится хорошо'],notifications:['Уведомления','уведомление колокольчик'],account_balance:['Банк','банк финансы'],credit_card:['Карта','карта оплата'],rocket:['Ракета','ракета запуск рост'],eco:['Экология','лист экология природа'],coffee:['Кофе','кофе чашка'],medical_services:['Медицина','медицина помощь'],
};

const friendlyName = name => RU_ICON_META[name]?.[0] || name.split('_').map(w => w.charAt(0).toUpperCase()+w.slice(1)).join(' ');
const WORDS_RU={account:'Аккаунт',add:'Добавить',air:'Воздух',alarm:'Будильник',arrow:'Стрелка',article:'Документ',back:'Назад',badge:'Сотрудник',balance:'Баланс',bar:'Столбчатый',battery:'Батарея',book:'Книга',business:'Бизнес',calendar:'Календарь',call:'Звонок',camera:'Камера',car:'Автомобиль',chart:'График',check:'Готово',circle:'Круг',cloud:'Облако',code:'Код',computer:'Компьютер',content:'Содержимое',credit:'Кредитная',dashboard:'Панель',data:'Данные',delete:'Удалить',description:'Документ',device:'Устройство',directions:'Направление',document:'Документ',download:'Скачать',edit:'Редактировать',email:'Почта',error:'Ошибка',event:'Событие',favorite:'Избранное',file:'Файл',filter:'Фильтр',flight:'Самолёт',folder:'Папка',format:'Формат',forward:'Вперёд',group:'Группа',help:'Помощь',home:'Дом',image:'Изображение',info:'Информация',keyboard:'Клавиатура',language:'Язык',light:'Свет',link:'Ссылка',list:'Список',location:'Место',lock:'Замок',mail:'Почта',map:'Карта',menu:'Меню',money:'Деньги',more:'Ещё',notifications:'Уведомления',open:'Открыть',payments:'Платежи',person:'Человек',phone:'Телефон',photo:'Фото',play:'Воспроизвести',print:'Печать',refresh:'Обновить',remove:'Убрать',save:'Сохранить',search:'Поиск',security:'Безопасность',send:'Отправить',settings:'Настройки',share:'Поделиться',shopping:'Покупки',star:'Звезда',text:'Текст',time:'Время',travel:'Путешествия',upload:'Загрузить',verified:'Подтверждено',video:'Видео',visibility:'Видимость',volume:'Громкость',warning:'Внимание',wifi:'Wi-Fi',work:'Работа'};
const SEARCH_GROUPS={
 'деньги финансы оплата платёж платежи':['payments','attach_money','paid','savings','account_balance','account_balance_wallet','wallet','credit_card','currency_ruble'],
 'сотрудник сотрудники человек люди пользователь':['person','badge','account_circle','groups','group','supervisor_account','diversity'],
 'команда коллектив группа':['groups','group','diversity','supervisor_account'],
 'документ документы файл договор':['description','article','draft','contract','file_copy','folder','note'],
 'график диаграмма статистика аналитика':['bar_chart','pie_chart','analytics','monitoring','show_chart','trending_up'],
 'строительство стройка здание':['construction','engineering','architecture','foundation','apartment'],
 'телефон звонок связь':['phone','call','smartphone','contact_phone']
};
function translatedTitle(name){
 if(RU_ICON_META[name])return RU_ICON_META[name][0];
 const words=name.split('_'), translated=words.map(w=>WORDS_RU[w]).filter(Boolean);
 return translated.length?translated.join(' '):'Значок';
}
function extraKeywords(name){return Object.entries(SEARCH_GROUPS).filter(([,names])=>names.some(n=>name===n||name.startsWith(n+'_'))).map(([words])=>words).join(' ')}
const normalizedCategories = ICON_CATEGORIES.map(([title,description,names], categoryIndex)=>({title,description,icons:names.split(' ').map(name=>({name,title:translatedTitle(name),keywords:`${RU_ICON_META[name]?.[1]||''} ${extraKeywords(name)} ${name.replaceAll('_',' ')}`,category:title,categoryIndex}))}));
let ICONS = [...new Map(normalizedCategories.flatMap(c=>c.icons).map(i=>[i.name,i])).values()];

/* The official catalog remains the source of truth and is merged with the curated RU catalog. */
async function loadOfficialIcons(){
 const response=await fetch('https://fonts.google.com/metadata/icons');
 if(!response.ok)throw new Error(`Google catalog: ${response.status}`);
 const raw=await response.text(), json=JSON.parse(raw.replace(/^\)\]\}'\s*/,''));
 const official=Array.isArray(json.icons)?json.icons:[];
 if(!official.length)throw new Error('Google catalog is empty');
 const byName=new Map(ICONS.map(icon=>[icon.name,icon]));
 official.forEach(item=>{
  if(byName.has(item.name))return;
  const rawCategory=(item.categories||[])[0]||'';
  const categoryIndex=/social/i.test(rawCategory)?2:/communication/i.test(rawCategory)?4:/image/i.test(rawCategory)?5:/maps/i.test(rawCategory)?7:/av/i.test(rawCategory)?9:/transport/i.test(rawCategory)?10:/hardware/i.test(rawCategory)?13:/home/i.test(rawCategory)?16:/action/i.test(rawCategory)?3:11;
  const category=normalizedCategories[categoryIndex];
  const icon={name:item.name,title:translatedTitle(item.name),keywords:`${(item.tags||[]).join(' ')} ${extraKeywords(item.name)} ${item.name.replaceAll('_',' ')}`,category:category.title,categoryIndex};
  category.icons.push(icon);byName.set(icon.name,icon);
 });
 ICONS=[...byName.values()];return ICONS;
}
