/* Add icons by appending Material Symbol names to a category. Russian metadata is separate. */
const ICON_CATEGORIES = [
['Популярные иконки для презентаций','Самые нужные знаки для слайдов и документов','search home menu close check add remove arrow_forward arrow_back star favorite person groups phone mail location_on calendar_today schedule info warning help settings download upload share link visibility edit delete lock payments trending_up bar_chart pie_chart lightbulb school'],
['Элементы интерфейса','Кнопки, стрелки, меню и элементы навигации','menu more_vert more_horiz close check add remove expand_more expand_less chevron_left chevron_right arrow_upward arrow_downward arrow_back arrow_forward first_page last_page refresh sync undo redo fullscreen fullscreen_exit open_in_new launch drag_indicator apps filter_list sort tune toggle_on toggle_off radio_button_checked check_box cancel done_all'],
['Люди и соцсети','Пользователи, команды и эмоции','person groups group person_add person_remove account_circle face mood sentiment_satisfied sentiment_dissatisfied diversity_1 diversity_2 diversity_3 handshake waving_hand thumb_up thumb_down public language share social_distance psychology accessibility child_care elderly woman man badge contacts supervisor_account engineering'],
['Действия','Частые команды и операции','search edit delete save print download upload content_copy content_paste content_cut add_circle remove_circle play_arrow pause stop restart_alt cached autorenew zoom_in zoom_out pan_tool touch_app login logout send reply forward archive inventory bookmark flag push_pin attach_file create brush build done select_all history restore publish'],
['Общение и связь','Почта, звонки, чаты и уведомления','phone call call_end smartphone mail email inbox drafts mark_email_read chat forum comment sms message notifications notifications_off alternate_email contact_mail contact_phone voicemail wifi cellular_alt signal_cellular_alt rss_feed campaign record_voice_over support_agent live_help speaker_phone video_call phonelink ring_volume'],
['Изображения и фото','Фото, палитры и работа с изображениями','image photo camera_alt photo_camera collections gallery_thumbnail palette color_lens crop rotate_left rotate_right flip brightness_6 contrast filter_hdr landscape portrait panorama add_a_photo image_search slideshow auto_awesome remove_red_eye hide_image broken_image gradient texture looks exposure center_focus_strong flash_on movie_creation animation'],
['Бизнес и финансы','Деньги, отчёты, рост и работа','payments attach_money currency_ruble euro currency_exchange account_balance account_balance_wallet savings credit_card receipt receipt_long point_of_sale shopping_cart storefront business work briefcase trending_up trending_down query_stats analytics bar_chart pie_chart monitoring timeline show_chart leaderboard calculate percent request_quote paid sell local_offer inventory_2 factory'],
['Карты и места','Адреса, маршруты и объекты на карте','location_on place map navigation near_me directions route explore my_location pin_drop where_to_vote flag room travel_explore public terrain satellite_alt layers streetview restaurant local_cafe hotel local_hospital local_library local_parking local_gas_station local_mall park museum church apartment domain home_work'],
['Текст и форматирование','Текстовые блоки и оформление документов','title text_fields format_bold format_italic format_underlined format_strikethrough format_size format_color_text format_align_left format_align_center format_align_right format_align_justify format_list_bulleted format_list_numbered format_quote notes subject article description insert_link link_off table_chart view_column space_bar functions superscript subscript wrap_text spellcheck translate short_text segment'],
['Аудио и видео','Музыка, видео и управление воспроизведением','play_arrow pause stop fast_forward fast_rewind skip_next skip_previous replay volume_up volume_down volume_off mic mic_off headphones speaker music_note queue_music album video_library movie videocam videocam_off closed_caption subtitles high_quality speed shuffle repeat podcast live_tv radio equalizer graphic_eq'],
['Транспорт','Автомобили и городской транспорт','directions_car car_rental taxi_alert local_taxi bus_alert directions_bus train tram subway flight two_wheeler motorcycle pedal_bike electric_bike electric_scooter airport_shuttle local_shipping delivery_dining commute traffic garage tire_repair car_repair ev_station no_crash sailing directions_boat rocket railway_alert'],
['Занятия и досуг','Спорт, творчество, покупки и отдых','sports_soccer sports_basketball sports_tennis sports_esports fitness_center hiking pool surfing skiing golf_course stadia_controller casino celebration cake restaurant local_bar coffee theater_comedy music_note piano draw palette book menu_book shopping_bag pets eco spa campground kayaking chess toys'],
['Android и система','Системные состояния и управление устройством','android settings power_settings_new restart_alt update system_update security shield bug_report memory storage battery_full battery_charging_full wifi bluetooth data_usage network_check signal_cellular_alt airplane_mode brightness_auto dark_mode light_mode language accessibility key keyboard mouse screenshot developer_mode code terminal integration_instructions dataset cloud cloud_done backup'],
['Техника и гаджеты','Компьютеры, экраны и устройства','devices computer laptop desktop_windows monitor smartphone tablet watch tv connected_tv keyboard mouse headphones headset speaker router scanner print camera phone_iphone phone_android smart_display smart_toy memory usb cable cast cast_connected dock gamepad thermostat sensors hub earbuds charging_station'],
['Безопасность','Защита, доступ и приватность','lock lock_open key vpn_key password shield security verified_user admin_panel_settings privacy_tip fingerprint policy gpp_good gpp_bad encrypted no_encryption visibility visibility_off warning report problem dangerous health_and_safety emergency passkey login logout person_off block do_not_disturb password'],
['Путешествия','Поездки, багаж, отели и направления','flight flight_takeoff flight_land luggage travel_explore hotel bed beach_access map public language passport connecting_airports departure_board train directions_boat sailing airport_shuttle local_taxi restaurant museum attractions hiking campground photo_camera explore navigation location_on festival currency_exchange'],
['Дом и быт','Комнаты, мебель и домашние дела','home apartment cottage house door_front living kitchen chair bed bedroom_parent bathroom shower bathtub weekend table_restaurant desk light cleaning_services vacuum local_laundry_service iron checkroom microwave blender coffee flatware grocery water_drop yard deck fence roofing garage foundation'],
['Умный дом','Датчики, климат и подключённые устройства','home_iot_device thermostat device_thermostat sensors sensor_door sensor_window lightbulb light_mode mode_fan air ac_unit heat_pump water_drop sprinkler nest_cam_indoor nest_cam_outdoor doorbell camera_outdoor detector_smoke detector_alarm electric_meter energy_savings_leaf wifi router hub smart_toy speaker tv remote_gen security lock blinds curtains'],
];

const RU_ICON_META = {
 search:['Поиск','поиск лупа найти искать'],home:['Дом','дом жильё главная'],phone:['Телефон','телефон звонок связь'],payments:['Деньги','деньги оплата финансы платёж'],person:['Человек','человек сотрудник пользователь'],groups:['Команда','команда люди сотрудники группа'],warning:['Внимание','внимание предупреждение опасность'],school:['Обучение','обучение образование школа'],settings:['Настройки','настройки параметры'],favorite:['Избранное','сердце любовь избранное'],star:['Звезда','звезда рейтинг'],mail:['Почта','почта письмо email'],location_on:['Место','место адрес геолокация'],calendar_today:['Календарь','календарь дата'],schedule:['Время','время часы расписание'],info:['Информация','информация сведения'],help:['Помощь','помощь вопрос'],download:['Скачать','скачать загрузить'],upload:['Загрузить','загрузить отправить'],share:['Поделиться','поделиться ссылка'],visibility:['Просмотр','глаз просмотр видимость'],edit:['Редактировать','карандаш изменить'],delete:['Удалить','корзина удалить'],lock:['Замок','замок безопасность'],trending_up:['Рост','рост график'],bar_chart:['Диаграмма','диаграмма график данные'],pie_chart:['Круговая диаграмма','диаграмма доли'],lightbulb:['Идея','идея лампочка'],menu:['Меню','меню навигация'],close:['Закрыть','закрыть крестик'],check:['Готово','галочка готово да'],add:['Добавить','плюс добавить'],remove:['Убрать','минус убрать'],arrow_forward:['Стрелка вправо','стрелка далее вправо'],arrow_back:['Стрелка влево','стрелка назад влево'],business:['Бизнес','бизнес компания офис'],work:['Работа','работа портфель'],analytics:['Аналитика','аналитика данные отчёт'],chat:['Чат','чат общение сообщение'],camera_alt:['Камера','камера фото'],image:['Изображение','изображение картинка фото'],play_arrow:['Воспроизвести','пуск видео играть'],pause:['Пауза','пауза остановить'],directions_car:['Автомобиль','машина автомобиль транспорт'],flight:['Самолёт','самолёт полёт путешествие'],security:['Безопасность','безопасность защита'],palette:['Палитра','палитра цвет дизайн'],shopping_cart:['Корзина','покупка корзина магазин'],public:['Мир','мир глобус земля'],language:['Язык','язык перевод мир'],key:['Ключ','ключ доступ безопасность'],wifi:['Wi-Fi','интернет сеть вайфай'],print:['Печать','печать принтер'],save:['Сохранить','сохранить дискета'],thumb_up:['Нравится','лайк нравится хорошо'],notifications:['Уведомления','уведомление колокольчик'],account_balance:['Банк','банк финансы'],credit_card:['Карта','карта оплата'],rocket:['Ракета','ракета запуск рост'],eco:['Экология','лист экология природа'],coffee:['Кофе','кофе чашка'],medical_services:['Медицина','медицина помощь'],
};

const friendlyName = name => RU_ICON_META[name]?.[0] || name.split('_').map(w => w.charAt(0).toUpperCase()+w.slice(1)).join(' ');
const WORDS_RU={account:'Аккаунт',add:'Добавить',air:'Воздух',alarm:'Будильник',arrow:'Стрелка',article:'Документ',back:'Назад',badge:'Сотрудник',balance:'Баланс',bar:'Столбчатый',battery:'Батарея',book:'Книга',business:'Бизнес',calendar:'Календарь',call:'Звонок',camera:'Камера',car:'Автомобиль',chart:'График',check:'Готово',circle:'Круг',cloud:'Облако',code:'Код',computer:'Компьютер',content:'Содержимое',credit:'Кредитная',dashboard:'Панель',data:'Данные',delete:'Удалить',description:'Документ',device:'Устройство',directions:'Направление',document:'Документ',download:'Скачать',edit:'Редактировать',email:'Почта',error:'Ошибка',event:'Событие',favorite:'Избранное',file:'Файл',filter:'Фильтр',flight:'Самолёт',folder:'Папка',format:'Формат',forward:'Вперёд',group:'Группа',help:'Помощь',home:'Дом',image:'Изображение',info:'Информация',keyboard:'Клавиатура',language:'Язык',light:'Свет',link:'Ссылка',list:'Список',location:'Место',lock:'Замок',mail:'Почта',map:'Карта',menu:'Меню',money:'Деньги',more:'Ещё',notifications:'Уведомления',open:'Открыть',payments:'Платежи',person:'Человек',phone:'Телефон',photo:'Фото',play:'Воспроизвести',print:'Печать',refresh:'Обновить',remove:'Убрать',save:'Сохранить',search:'Поиск',security:'Безопасность',send:'Отправить',settings:'Настройки',share:'Поделиться',shopping:'Покупки',star:'Звезда',text:'Текст',time:'Время',travel:'Путешествия',upload:'Загрузить',verified:'Подтверждено',video:'Видео',visibility:'Видимость',volume:'Громкость',warning:'Внимание',wifi:'Wi-Fi',work:'Работа'};
const SEARCH_GROUPS={
 'деньги финансы оплата платёж платежи':['payments','attach_money','paid','savings','account_balance','account_balance_wallet','wallet','credit_card','currency_ruble'],
 'сотрудник сотрудники человек люди пользователь':['person','badge','account_circle','groups','group','supervisor_account','diversity'],
 'команда коллектив группа':['groups','group','diversity','supervisor_account'],
 'документ документы файл договор':['description','article','draft','contract','file_copy','folder','note'],
 'график диаграмма статистика аналитика':['bar_chart','pie_chart','analytics','monitoring','show_chart','trending_up'],
 'строительство стройка здание':['construction','engineering','architecture','foundation','apartment'],
 'телефон звонок связь':['phone','call','smartphone','contact_phone']
};
Object.assign(WORDS_RU,{
 activity:'Активность',alert:'Предупреждение',analytics:'Аналитика',apartment:'Здание',archive:'Архив',architecture:'Архитектура',attach:'Прикрепить',audio:'Аудио',backup:'Резервная копия',bluetooth:'Bluetooth',bookmark:'Закладка',border:'Граница',brightness:'Яркость',brush:'Кисть',build:'Инструменты',button:'Кнопка',cancel:'Отмена',card:'Карта',category:'Категория',cell:'Сотовая связь',chat:'Чат',child:'Ребёнок',clean:'Очистить',clock:'Часы',comment:'Комментарий',communication:'Связь',construction:'Строительство',contact:'Контакт',contrast:'Контраст',copy:'Копировать',create:'Создать',currency:'Валюта',cut:'Вырезать',dark:'Тёмный',delivery:'Доставка',desktop:'Компьютер',done:'Готово',door:'Дверь',drag:'Перетащить',draw:'Рисовать',earth:'Земля',elderly:'Пожилой',emergency:'Экстренно',engineering:'Инженерия',expand:'Развернуть',explore:'Исследовать',factory:'Производство',family:'Семья',finance:'Финансы',fingerprint:'Отпечаток',flag:'Флаг',food:'Еда',foundation:'Фундамент',fullscreen:'Полный экран',game:'Игра',garage:'Гараж',grade:'Оценка',graph:'График',hardware:'Оборудование',headphones:'Наушники',history:'История',hotel:'Отель',house:'Дом',inventory:'Склад',key:'Ключ',kitchen:'Кухня',laptop:'Ноутбук',layers:'Слои',login:'Вход',logout:'Выход',medical:'Медицина',message:'Сообщение',mic:'Микрофон',mobile:'Мобильный',monitor:'Монитор',mood:'Настроение',move:'Переместить',movie:'Видео',music:'Музыка',navigation:'Навигация',network:'Сеть',notification:'Уведомление',notes:'Заметки',pause:'Пауза',payment:'Платёж',people:'Люди',place:'Место',policy:'Правила',power:'Питание',privacy:'Приватность',public:'Мир',publish:'Опубликовать',qr:'QR',radio:'Радио',receipt:'Чек',record:'Запись',reply:'Ответить',report:'Отчёт',restore:'Восстановить',route:'Маршрут',school:'Обучение',screen:'Экран',shopping:'Покупки',signal:'Сигнал',smart:'Умный',speaker:'Динамик',sports:'Спорт',stop:'Стоп',store:'Магазин',sync:'Синхронизация',system:'Система',tablet:'Планшет',task:'Задача',terminal:'Терминал',thermostat:'Термостат',timer:'Таймер',train:'Поезд',transport:'Транспорт',trash:'Корзина',tune:'Настройка',undo:'Отменить',user:'Пользователь',vehicle:'Транспорт',verified:'Подтверждено',view:'Просмотр',wallet:'Кошелёк',water:'Вода',weather:'Погода',window:'Окно',woman:'Женщина',man:'Мужчина',boy:'Мальчик',girl:'Девочка',zoom:'Масштаб'
});
const ACRONYMS={wifi:'Wi-Fi',usb:'USB',qr:'QR',hd:'HD',hdr:'HDR',vpn:'VPN',sms:'SMS',nfc:'NFC',gps:'GPS',api:'API',apk:'APK',ios:'iOS',android:'Android',ai:'AI',ar:'AR',vr:'VR',tv:'TV',id:'ID','2d':'2D','3d':'3D','4k':'4K','5g':'5G'};
function humanToken(token){const low=token.toLowerCase();if(ACRONYMS[low])return ACRONYMS[low];if(/^\d+(k|mp)$/i.test(token))return token.toUpperCase();return token.charAt(0).toUpperCase()+token.slice(1)}
function translatedTitle(name){if(RU_ICON_META[name])return RU_ICON_META[name][0];return name.split('_').filter(Boolean).map(token=>WORDS_RU[token.toLowerCase()]||ACRONYMS[token.toLowerCase()]||humanToken(token)).join(' ')||friendlyName(name)}
function extraKeywords(name){return Object.entries(SEARCH_GROUPS).filter(([,names])=>names.some(n=>name===n||name.startsWith(n+'_'))).map(([words])=>words).join(' ')}
const normalizedCategories=ICON_CATEGORIES.map(([title,description,names],categoryIndex)=>({title,description,icons:names.split(' ').map(name=>({name,title:translatedTitle(name),keywords:`${RU_ICON_META[name]?.[1]||''} ${extraKeywords(name)} ${name.replaceAll('_',' ')}`,category:title,categoryIndex}))}));
normalizedCategories.push({title:'Другие иконки',description:'Остальные иконки полного каталога Material Symbols',icons:[]});
const OTHER_CATEGORY_INDEX=normalizedCategories.length-1;
function categoryForName(name){const rules=[
[17,/(home_iot|nest_|thermostat|sensor|sprinkler|doorbell|detector|electric_meter|energy_savings|blinds|curtains|smart_outlet|hvac|heat_pump|air_purifier|water_heater)/],
[14,/(^|_)(lock|key|password|shield|security|verified|privacy|fingerprint|policy|gpp|encrypt|warning|report|danger|emergency|passkey|login|logout|block|phishing|safety|vpn)(_|$)/],
[15,/(flight|luggage|travel|hotel|beach|passport|connecting_airports|departure|sailing|airport|attraction|tour|trip)/],
[10,/(directions_(car|bus|railway|boat|bike)|(^|_)(car|bus|train|tram|subway|bike|scooter|motorcycle|taxi|shipping|delivery|traffic|garage|tire|boat|railway|transport|commute|moped)(_|$)|^ev_|airport_shuttle)/],
[9,/(^|_)(play|pause|stop|video|audio|music|mic|volume|movie|media|podcast|radio|headphones|speaker|subtitle|caption|replay|skip|record|equalizer)(_|$)|fast_forward|fast_rewind|graphic_eq/],
[5,/(^|_)(image|photo|camera|palette|color|crop|rotate|flip|brightness|contrast|filter|landscape|portrait|panorama|slideshow|gradient|texture|exposure|animation)(_|$)|movie_creation/],
[6,/(payment|money|currency|account_balance|wallet|saving|credit|receipt|sale|shopping|store|business|work|finance|analytics|chart|trending|percent|factory|inventory|calculate|paid|sell|price|quote)/],
[7,/(location|place|^map$|navigation|route|explore|pin_drop|where_to_vote|terrain|satellite|streetview|^local_|park|museum|church|domain|layers)/],
[8,/(^|_)(text|format|title|subject|article|description|document|note|table|column|row|space|function|spell|translate|paragraph|font|list|quote|markdown)(_|$)|insert_link|link_off/],
[4,/(mail|email|chat|message|sms|call|phone|notification|forum|voicemail|contact|campaign|rss_feed|communication)/],
[2,/(person|people|group|face|mood|sentiment|diversity|woman|man|child|family|social|accessibility|elderly|boy|girl|badge|contacts|handshake|waving_hand)/],
[16,/(^|_)(home|apartment|cottage|house|door|living|kitchen|chair|bedroom|bath|shower|desk|clean|vacuum|laundry|iron|microwave|blender|flatware|grocery|yard|deck|fence|roof|foundation|household|faucet|oven|dishwasher)(_|$)/],
[13,/(device|computer|laptop|desktop|monitor|smartphone|tablet|watch|^tv$|keyboard|mouse|headset|router|scanner|printer|phone_iphone|phone_android|smart_display|smart_toy|usb|cable|cast|dock|gamepad|hardware|screen|display|earbud|charging)/],
[12,/(android|system|power|restart|update|bug|memory|storage|battery|network|signal|airplane|dark_mode|light_mode|developer|code|terminal|dataset|cloud|backup|bluetooth|data_usage)/],
[11,/(sports|fitness|hiking|pool|surf|ski|golf|casino|celebration|cake|restaurant|local_bar|coffee|theater|piano|draw|pets|eco|spa|camp|kayak|chess|toys|game|stadium|festival|dining|food)/],
[1,/(menu|more_|close|check|expand|chevron|arrow|page|refresh|undo|redo|fullscreen|open_in_new|launch|drag|apps|filter|sort|tune|toggle|radio_button|check_box|cancel|done|view_|dashboard|^tab|window|panel|toolbar|button|select|switch|dropdown)/],
[3,/(edit|delete|save|download|upload|copy|paste|cut|zoom|touch|send|reply|forward|archive|bookmark|flag|push_pin|attach|create|brush|build|history|restore|publish|search|share|print|move|scan|schedule|task)/]
];for(const [index,re] of rules)if(re.test(name))return index;return OTHER_CATEGORY_INDEX}
let ICONS=[];
async function loadOfficialIcons(){if(!Array.isArray(MATERIAL_SYMBOL_NAMES)||MATERIAL_SYMBOL_NAMES.length<4000)throw new Error('Локальный каталог Material Symbols неполный');const officialSet=new Set(MATERIAL_SYMBOL_NAMES);normalizedCategories.slice(0,OTHER_CATEGORY_INDEX).forEach(category=>{category.icons=category.icons.filter(icon=>officialSet.has(icon.name))});normalizedCategories[OTHER_CATEGORY_INDEX].icons=[];const byName=new Map();normalizedCategories.slice(0,OTHER_CATEGORY_INDEX).forEach(category=>category.icons.forEach(icon=>byName.set(icon.name,icon)));for(const name of MATERIAL_SYMBOL_NAMES){if(byName.has(name))continue;const categoryIndex=categoryForName(name),category=normalizedCategories[categoryIndex],title=translatedTitle(name);const icon={name,title,keywords:`${RU_ICON_META[name]?.[1]||''} ${extraKeywords(name)} ${name.replaceAll('_',' ')} ${title}`,category:category.title,categoryIndex};category.icons.push(icon);byName.set(name,icon)}ICONS=[...byName.values()];return ICONS}
